[package]
name = "minimal"
version = "0.1.0"
edition = "2024"

[dependencies]
isideload = { path = "../../isideload" }
plist-macro = "0.1.3"
tokio = { version = "1.49.0", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
