[package]
name = "minimal"
version = "0.1.0"
edition = "2024"

[dependencies]
isideload = { path = "../../isideload" }
env_logger = "0.11.8"
tokio = { version = "1.49.0", features = ["rt-multi-thread", "macros"] }
