[package]
name = "isideload"
description = "Sideload iOS/iPadOS applications"
license = "MIT"
authors = ["Nicholas Sharp <nab@nabdev.me>"]
version = "0.2.0"
edition = "2024"
repository = "https://github.com/nab138/isideload"
documentation = "https://docs.rs/isideload"
keywords = ["ios", "sideload"]
readme = "../README.md"

[features]
default = ["install"]
install = ["dep:idevice"]

[dependencies]
idevice = { version = "0.1.50", optional = true }
plist = "1.8.0"
plist-macro = "0.1.0"
reqwest = { version = "0.13.1", features = ["json", "gzip"] }
thiserror = "2.0.17"
